### ISSUE TITLE
installing pointops

### ISSUE THREAD

**Issue by XiShuFan** [limhoyeon/ToothGroupNetwork#24]
I have same pytorch and cuda versions on Windows and Ubuntu.

Pointops could be installed correctly and worked correctly on Windows, but when I use Ubuntu, it could be installed correctly but worked incorrectly.

To be detail, pointops_cuda functions throws "CUDA error: no kernel image is available for execution on the device"

People who encountered this problem could try to install original pointops from https://github.com/POSTECH-CVLab/point-transformer/tree/master/lib, that works for me.

**Comment by VGTHuang** [comment]
Thank you! It is most helpful. Installing pointops from the repository works. During installing, the error
```
“THC/THC.h”: No such file or directory
```
could be solved by removing all
```
include <THC/THC.h>
```

**Comment by XiShuFan** [comment]
> Thank you! It is most helpful. Installing pointops from the repository works. During installing, the error
> 
> ```
> “THC/THC.h”: No such file or directory
> ```
> 
> could be solved by removing all
> 
> ```
> include <THC/THC.h>
> ```

Thanks for your solution for "THC/THC.h”: No such file or directory"
Yes, I encountered the same problem with pytorch 1.13 and cuda 11.3
I solved this problem with pytorch 1.7.1 and cuda 11.0

```
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
```

**Comment by aanandaathmaram** [comment]
File "setup.py", line 9, in <module>
    flag for flag in opt.split() if flag != '-Wstrict-prototypes'
AttributeError: 'NoneType' object has no attribute 'split'

Any way to tackle this issue?

**Comment by limhoyeon** [comment]
@aanandaathmaram 
have you solved this issue now?

**Comment by aanandaathmaram** [comment]
> @aanandaathmaram 
> have you solved this issue now?

Not yet

**Comment by limhoyeon** [comment]
I think that you should recheck the pytorch - cuda - python version.
How about following each version to pytorch/pytorch:1.7.1-cuda11.0-cudnn8-devel(ubuntu, pytorch 1.7.1) docker settings?

**Comment by smoothumut** [comment]
removing all lines about including THC in pointops library solve my issue also

include <THC/THC.h>

**Comment by qwercz** [comment]
运行setup.py后出现src/pointops_api.cpp:2:10: fatal error: knnquery/knnquery_cuda_kernel.h: No such file or directory
 #include "knnquery/knnquery_cuda_kernel.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1，请问该怎么解决呀
